import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ralawey = localFont({
  src: "../app/fonts/Raleway.woff2",
  variable: "--font-releway",
  weight: "100 900",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        cz-shortcut-listen="true"
        className={`${ralawey.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
